name: Node.js CI

on:
  push:
    branches:["main"]
  pull_request:
    branches:["main"]

jobs:
  build:
    runs-on: self-hosted-linux

    steps:
      - uses: actions/checkout@v2
      - name: Node.js CI
        uses: actions/node-@v1
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - run: |
          npm install
          cd client
          npm install
          npm run build
          
                          


