name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Node.js CI
        uses: actions/node-@v1
        with:
          node-version: ${{ matrix.NODE_VERSION }}
      - run: |
          npm install
          cd client
          npm install
          npm run build
          
                          


